# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  schedule:
    - cron: "*/28 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          sudo apt-get install -y curl ca-certificates
          sudo curl --silent --show-error --fail myresearch2-production.up.railway.app
          sudo curl --silent --show-error --fail myresearch2-production-8946.up.railway.app
          sudo curl --silent --show-error --fail myresearch2-production-2327.up.railway.app
          sudo curl --silent --show-error --fail myresearch2-production-b8d4.up.railway.app
          sudo curl --silent --show-error --fail myresearch2-production-b866.up.railway.app
          sudo curl --silent --show-error --fail myresearch2-production-499e.up.railway.app
          sudo curl --silent --show-error --fail myresearch2-production-970f.up.railway.app
          sudo curl --silent --show-error --fail lvlinapp1.herokuapp.com
          sudo curl --silent --show-error --fail lvlinapp2.herokuapp.com
          sudo curl --silent --show-error --fail lvlinapp3.herokuapp.com
          sudo curl --silent --show-error --fail lvlinapp4.herokuapp.com
          sudo curl --silent --show-error --fail lvlinapp5.herokuapp.com
          sudo curl --silent --show-error --fail lvlin01.herokuapp.com
          sudo curl --silent --show-error --fail lvlin02.herokuapp.com
          sudo curl --silent --show-error --fail lvlin03.herokuapp.com
          sudo curl --silent --show-error --fail lvlin04.herokuapp.com
          sudo curl --silent --show-error --fail lvlin05.herokuapp.com
          sudo curl --silent --show-error --fail lvlin06.herokuapp.com
          sudo curl --silent --show-error --fail lvlin07.herokuapp.com
          sudo curl --silent --show-error --fail cdnh1.lvlin.workers.dev
          sudo curl --silent --show-error --fail cdnr1.lvlin.workers.dev
